# Generated by Django 5.2.3 on 2025-06-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_project_category_project_client_project_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accordion_1_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='accordion_1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='accordion_2_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='accordion_2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='accordion_3_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='accordion_3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
    ]
