# Generated by Django 5.2.3 on 2025-06-17 21:11

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_project_accordion_1_body_project_accordion_1_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='projects/gallery/'),
        ),
    ]
