# Generated by Django 5.2.3 on 2025-06-17 23:39

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_remove_project_image_project_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_media',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='projects/featured/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4'])]),
        ),
    ]
