# Generated by Django 5.2.3 on 2025-11-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_project_featured_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='popup_blurb',
            field=models.TextField(blank=True, help_text='Short description for the popup (optional, uses main description if empty)'),
        ),
        migrations.AddField(
            model_name='project',
            name='popup_featured',
            field=models.BooleanField(default=False, help_text='Show this project in a popup on the portfolio page'),
        ),
    ]
